### ISSUE TITLE
Simplify CSS for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [joelljones/prj-rev-bwfs-dasmoto#5]
It is always a good idea to try and simplify the CSS code as much as possible to make the code cleaner and to remove repetitive code. For instance, the font-family and font-weight properties are shared by multiple elements. You can simplify it like

```css
h1, h2, p, h3, .price {
  font-family: Helvetica;
  font-weight: bold;
}
```
